# Site settings
title: Planetary Rings Node
email: lballard@seti.org
description: > # this means to ignore newlines until "baseurl:"
    The Planetary Rings Node of NASA's Planetary Data System is devoted to archiving, cataloging, and distributing scientific data sets relevant to planetary ring systems.
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
keep_files: []

# copy this and remove the one you want to watch during jekyll serve --watch
# exclude: [rpx, roses, ringocc, resonance, newhorizons, neptune, jupiter, hst, glossary.html, galileo, feed.xml, cassini, astrometry, urpx, uranus, tools, toolkits, saturn, voyager]
exclude: [roses, ringocc, resonance, neptune, jupiter, glossary.html, feed.xml, cassini, astrometry, uranus, tools, toolkits, saturn, voyager]
